package com.esifit.data;

import com.esifit.model.Member;
import com.esifit.model.Visit;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.UUID;

public final class Database {
    private final String url;

    public Database(Path dataDirectory) {
        this(databaseUrl(dataDirectory));
    }

    private static String databaseUrl(Path dataDirectory) {
        try {
            Files.createDirectories(dataDirectory);
        } catch (IOException error) {
            throw new IllegalStateException("Could not create the ESI-FIT data directory.", error);
        }
        return "jdbc:h2:file:" + dataDirectory.resolve("esi-fit").toAbsolutePath().toString().replace('\\', '/') +
                ";DB_CLOSE_ON_EXIT=FALSE";
    }

    public Database(String jdbcUrl) {
        this.url = jdbcUrl;
        initialize();
    }

    private void initialize() {
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS members (
                      id VARCHAR(24) PRIMARY KEY,
                      first_name VARCHAR(100) NOT NULL,
                      last_name VARCHAR(100) NOT NULL,
                      email VARCHAR(180) NOT NULL DEFAULT '',
                      plan VARCHAR(40) NOT NULL,
                      joined_on DATE NOT NULL,
                      active BOOLEAN NOT NULL DEFAULT TRUE
                    )
                    """);
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS visits (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      member_id VARCHAR(24) NOT NULL,
                      check_in TIMESTAMP NOT NULL,
                      check_out TIMESTAMP NULL,
                      CONSTRAINT fk_visit_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE
                    )
                    """);
            statement.executeUpdate("CREATE INDEX IF NOT EXISTS idx_visits_member ON visits(member_id)");
            statement.executeUpdate("CREATE INDEX IF NOT EXISTS idx_visits_open ON visits(member_id, check_out)");
        } catch (SQLException error) {
            throw databaseError(error);
        }
    }

    public Member addMember(String firstName, String lastName, String email, String plan) {
        var member = new Member(nextId(), clean(firstName), clean(lastName), clean(email), clean(plan), LocalDate.now(), true);
        if (member.firstName().isBlank() || member.lastName().isBlank())
            throw new IllegalArgumentException("First and last name are required.");

        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO members(id, first_name, last_name, email, plan, joined_on, active) VALUES(?,?,?,?,?,?,?)")) {
            statement.setString(1, member.id());
            statement.setString(2, member.firstName());
            statement.setString(3, member.lastName());
            statement.setString(4, member.email());
            statement.setString(5, member.plan());
            statement.setDate(6, Date.valueOf(member.joinedOn()));
            statement.setBoolean(7, true);
            statement.executeUpdate();
            return member;
        } catch (SQLException error) {
            throw databaseError(error);
        }
    }

    public List<Member> members(String search) {
        var query = clean(search).toLowerCase(Locale.ROOT);
        var sql = """
                SELECT * FROM members
                WHERE ? = '' OR LOWER(first_name || ' ' || last_name || ' ' || id || ' ' || email) LIKE ?
                ORDER BY active DESC, last_name, first_name
                """;
        var members = new ArrayList<Member>();
        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, query);
            statement.setString(2, "%" + query + "%");
            try (ResultSet results = statement.executeQuery()) {
                while (results.next()) members.add(readMember(results));
            }
            return members;
        } catch (SQLException error) {
            throw databaseError(error);
        }
    }

    public Member member(String id) {
        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(
                "SELECT * FROM members WHERE id = ?")) {
            statement.setString(1, id);
            try (ResultSet results = statement.executeQuery()) {
                return results.next() ? readMember(results) : null;
            }
        } catch (SQLException error) {
            throw databaseError(error);
        }
    }

    public void setMemberActive(String id, boolean active) {
        execute("UPDATE members SET active = ? WHERE id = ?", active, id);
    }

    public void deleteMember(String id) {
        execute("DELETE FROM members WHERE id = ?", id);
    }

    public boolean checkIn(String memberId) {
        if (member(memberId) == null) throw new IllegalArgumentException("Member not found.");
        try (Connection connection = connection()) {
            try (PreparedStatement open = connection.prepareStatement(
                    "SELECT COUNT(*) FROM visits WHERE member_id = ? AND check_out IS NULL")) {
                open.setString(1, memberId);
                try (ResultSet result = open.executeQuery()) {
                    result.next();
                    if (result.getInt(1) > 0) return false;
                }
            }
            try (PreparedStatement insert = connection.prepareStatement(
                    "INSERT INTO visits(member_id, check_in) VALUES(?, ?)")) {
                insert.setString(1, memberId);
                insert.setTimestamp(2, Timestamp.valueOf(LocalDateTime.now()));
                insert.executeUpdate();
                return true;
            }
        } catch (SQLException error) {
            throw databaseError(error);
        }
    }

    public boolean checkOut(String memberId) {
        var sql = """
                UPDATE visits SET check_out = ?
                WHERE id = (SELECT id FROM visits WHERE member_id = ? AND check_out IS NULL ORDER BY check_in DESC LIMIT 1)
                """;
        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setTimestamp(1, Timestamp.valueOf(LocalDateTime.now()));
            statement.setString(2, memberId);
            return statement.executeUpdate() > 0;
        } catch (SQLException error) {
            throw databaseError(error);
        }
    }

    public boolean isCheckedIn(String memberId) {
        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(
                "SELECT COUNT(*) FROM visits WHERE member_id = ? AND check_out IS NULL")) {
            statement.setString(1, memberId);
            try (ResultSet result = statement.executeQuery()) {
                result.next();
                return result.getInt(1) > 0;
            }
        } catch (SQLException error) {
            throw databaseError(error);
        }
    }

    public List<Visit> visits(int limit) {
        var sql = """
                SELECT v.id, v.member_id, m.first_name, m.last_name, v.check_in, v.check_out
                FROM visits v JOIN members m ON m.id = v.member_id
                ORDER BY v.check_in DESC LIMIT ?
                """;
        var visits = new ArrayList<Visit>();
        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setInt(1, Math.max(1, limit));
            try (ResultSet results = statement.executeQuery()) {
                while (results.next()) visits.add(readVisit(results));
            }
            return visits;
        } catch (SQLException error) {
            throw databaseError(error);
        }
    }

    public Metrics metrics() {
        var sql = """
                SELECT
                  (SELECT COUNT(*) FROM members WHERE active = TRUE) active_members,
                  (SELECT COUNT(*) FROM visits WHERE check_out IS NULL) checked_in,
                  (SELECT COUNT(*) FROM visits WHERE CAST(check_in AS DATE) = CURRENT_DATE) visits_today,
                  COALESCE((SELECT AVG(DATEDIFF(MINUTE, check_in, check_out)) FROM visits WHERE check_out IS NOT NULL), 0) average_minutes
                """;
        try (Connection connection = connection(); Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery(sql)) {
            result.next();
            return new Metrics(result.getInt(1), result.getInt(2), result.getInt(3), Math.round(result.getDouble(4)));
        } catch (SQLException error) {
            throw databaseError(error);
        }
    }

    public int memberCount() {
        try (Connection connection = connection(); Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery("SELECT COUNT(*) FROM members")) {
            result.next();
            return result.getInt(1);
        } catch (SQLException error) {
            throw databaseError(error);
        }
    }

    public int importLegacy(Path directory) {
        if (memberCount() > 0) return 0;
        var clientsFile = directory.resolve("clients.txt");
        if (!Files.isRegularFile(clientsFile)) return 0;
        var imported = 0;
        try {
            for (String line : Files.readAllLines(clientsFile, StandardCharsets.UTF_8)) {
                String[] parts = line.split("\\|", -1);
                if (parts.length < 3 || parts[0].isBlank()) continue;
                if (insertLegacyMember(parts[0].trim(), parts[1].trim(), parts[2].trim())) imported++;
            }
            importLegacySessions(directory.resolve("sessions.txt"));
            return imported;
        } catch (IOException error) {
            return imported;
        }
    }

    private boolean insertLegacyMember(String id, String firstName, String lastName) {
        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(
                "MERGE INTO members(id, first_name, last_name, email, plan, joined_on, active) KEY(id) VALUES(?,?,?,?,?,?,TRUE)")) {
            statement.setString(1, id);
            statement.setString(2, firstName);
            statement.setString(3, lastName);
            statement.setString(4, "");
            statement.setString(5, "Legacy");
            statement.setDate(6, Date.valueOf(LocalDate.now()));
            statement.executeUpdate();
            return true;
        } catch (SQLException error) {
            return false;
        }
    }

    private void importLegacySessions(Path file) {
        if (!Files.isRegularFile(file)) return;
        try {
            for (String line : Files.readAllLines(file, StandardCharsets.UTF_8)) {
                String[] parts = line.split("\\|", -1);
                if (parts.length < 3 || member(parts[0].trim()) == null) continue;
                LocalDateTime in = LocalDateTime.parse(parts[1].trim());
                LocalDateTime out = parts[2].trim().equals("null") ? null : LocalDateTime.parse(parts[2].trim());
                try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(
                        "INSERT INTO visits(member_id, check_in, check_out) VALUES(?,?,?)")) {
                    statement.setString(1, parts[0].trim());
                    statement.setTimestamp(2, Timestamp.valueOf(in));
                    statement.setTimestamp(3, out == null ? null : Timestamp.valueOf(out));
                    statement.executeUpdate();
                }
            }
        } catch (Exception ignored) {
            // A malformed historical row must never prevent the new app from starting.
        }
    }

    private void execute(String sql, Object... parameters) {
        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(sql)) {
            for (int index = 0; index < parameters.length; index++) statement.setObject(index + 1, parameters[index]);
            statement.executeUpdate();
        } catch (SQLException error) {
            throw databaseError(error);
        }
    }

    private Connection connection() throws SQLException {
        return DriverManager.getConnection(url, "sa", "");
    }

    private String nextId() {
        String id;
        do id = "EF-" + UUID.randomUUID().toString().substring(0, 6).toUpperCase(Locale.ROOT);
        while (member(id) != null);
        return id;
    }

    private static Member readMember(ResultSet result) throws SQLException {
        return new Member(result.getString("id"), result.getString("first_name"), result.getString("last_name"),
                result.getString("email"), result.getString("plan"), result.getDate("joined_on").toLocalDate(),
                result.getBoolean("active"));
    }

    private static Visit readVisit(ResultSet result) throws SQLException {
        Timestamp checkOut = result.getTimestamp("check_out");
        return new Visit(result.getLong("id"), result.getString("member_id"),
                result.getString("first_name") + " " + result.getString("last_name"),
                result.getTimestamp("check_in").toLocalDateTime(), checkOut == null ? null : checkOut.toLocalDateTime());
    }

    private static String clean(String value) {
        return value == null ? "" : value.trim();
    }

    private static IllegalStateException databaseError(SQLException error) {
        return new IllegalStateException("The local ESI-FIT database could not complete this operation.", error);
    }
}
